MODEL:
  TYPE: mbanynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: res_stem_in
  STEM_W: 64
  BLOCK_TYPE: res_bottleneck_block
  STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  DEPTHS: [[2, 3], [4, 3], [4, 4], [2, 1]]
  WIDTHS: [[192, 160], [320, 256], [896, 480], [1664, 1216]]
  BOT_MULS: [0.25, 0.25, 0.25, 0.25]
  GROUP_WS: [[48, 40], [80, 64], [224, 120], [416, 304]]
  DEVICES: ["cpu", "gpu"]
  HEAD_DEVICE: "cpu"
  STEM_DEVICE: "cpu"
  MERGE_DEVICE: "cpu"
  ORIGINAL_WIDTHS: [352, 576, 1376, 2880]
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.2
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 256
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 200
DATA_LOADER:
  MODE: ffcv
NUM_GPUS: 4
OUT_DIR: .
