MODEL:
  TYPE: mbanynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: simple_stem_in
  STEM_W: 32
  STEM_K: 3
  BLOCK_TYPE: res_bottleneck_block
  STRIDES: [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
  DEPTHS: [[2, 2, 2], [3, 5, 2], [8, 13, 5], [2, 2, 1]]
  WIDTHS: [[40, 40, 40], [160, 120, 80], [400, 240, 240], [960, 720, 640]]
  BOT_MULS: [1, 1, 1, 1]
  GROUP_WS: [[40, 40, 40], [40, 40, 40], [40, 40, 40], [40, 40, 40]]
  DEVICES: ["cpu", "dsp", "gpu"]
  HEAD_DEVICE: "cpu"
  STEM_DEVICE: "cpu"
  MERGE_DEVICE: "cpu"
  ORIGINAL_WIDTHS: [120, 360, 880, 2360]
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.8
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 1024
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 800
  POWERSAVE_LEVEL: 255
NUM_GPUS: 8
OUT_DIR: .
