MODEL:
  TYPE: mbanynet
  NUM_CLASSES: 1000
  ACTIVATION_FUN: relu
ANYNET:
  STEM_TYPE: simple_stem_in
  STEM_W: 32
  STEM_K: 3
  BLOCK_TYPE: mbconv
  STRIDES: [[1], [2], [2], [2], [1], [2], [1]]
  DEPTHS: [[1], [4], [4], [6], [6], [8], [1]]
  WIDTHS: [[24], [32], [56], [112], [160], [272], [448]]
  BOT_MULS: [1, 6, 6, 6, 6, 6, 6]
  KERNELS: [3, 3, 5, 3, 5, 5, 3]
  HEAD_W: 1280
  DEVICES: ["dsp"]
  HEAD_DEVICE: "dsp"
  STEM_DEVICE: "dsp"
  MERGE_DEVICE: "dsp"
  ORIGINAL_WIDTHS: [24, 32, 56, 112, 160, 272, 448]
  SE_ON: False
TRAIN:
  DATASET: imagenet
  IM_SIZE: 300
  BATCH_SIZE: 64
TEST:
  POWERSAVE_LEVEL: 128
