MODEL:
  TYPE: mbanynet
  NUM_CLASSES: 1000
  ACTIVATION_FUN: relu
ANYNET:
  STEM_TYPE: simple_stem_in
  STEM_W: 32
  STEM_K: 3
  BLOCK_TYPE: mbconv
  STRIDES: [[1], [2, 2], [2, 2], [2, 2], [1, 1], [2, 2], [1]]
  DEPTHS: [[1], [2, 3], [2, 3], [5, 5], [5, 4], [7, 5], [1]]
  WIDTHS: [[24], [32, 32], [48, 48], [96, 96], [120, 128], [232, 176], [448]]
  BOT_MULS: [1, 6, 6, 6, 6, 6, 6]
  KERNELS: [3, 3, 5, 3, 5, 5, 3]
  HEAD_W: 1280
  DEVICES: ["cpu", "gpu"]
  HEAD_DEVICE: "cpu"
  STEM_DEVICE: "cpu"
  MERGE_DEVICE: "cpu"
  ORIGINAL_WIDTHS: [24, 32, 56, 112, 160, 272, 448]
  SE_ON: False
  MB_VER: 1
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.1
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
TRAIN:
  DATASET: imagenet-tar
  IM_SIZE: 300
  BATCH_SIZE: 64
NUM_GPUS: 8
OUT_DIR: .
