MODEL:
  TYPE: mbanynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: res_stem_in
  STEM_W: 64
  BLOCK_TYPE: res_bottleneck_block
  STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  DEPTHS: [[3, 2], [3, 4], [4, 6], [2, 2]]
  WIDTHS: [[160, 224], [384, 256], [832, 512], [1632, 1184]]
  BOT_MULS: [0.25, 0.25, 0.25, 0.25]
  GROUP_WS: [[40, 56], [96, 64], [208, 128], [408, 296]]
  DEVICES: ["cpu", "dsp"]
  HEAD_DEVICE: "cpu"
  STEM_DEVICE: "cpu"
  MERGE_DEVICE: "cpu"
  ORIGINAL_WIDTHS: [384, 640, 1344, 2816]
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.2
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 256
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 200
DATA_LOADER:
  MODE: ffcv
NUM_GPUS: 4
OUT_DIR: .
